<a href="https://colab.research.google.com/github/niklasgrimm98/Digital-Organization/blob/main/Kopie_von_homework_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The following assignment consists again of a theoretical part (learning portfolio) and a practical part (assignment). The goal is to train a neural model from scratch, as we did a few weeks ago. I would like us to repeat the most important things so that we can consolidate our knowledge in this area, for this you will train a model on a dataset that I will provide via OLAT. 

The plan would be that in the first we will discuss your learnings from the theory part, that means you are relatively free to fill your Learning Portfolio on this topic and in the following week we will discuss your solutions of the Classification Model.

#Theory part (filling your Learning Portfolio, May 24)

In preparation for the practical part, I ask you to familiarize yourself with the following video sources in the next week:

1) Please watch the following video until random forests:

https://course.fast.ai/Lessons/lesson5.html

2) Please download the following notebooks and edit it in Google-Colab. Take notes and update your Learning Portfolio.

https://www.kaggle.com/code/jhoward/linear-model-and-neural-net-from-scratch

https://www.kaggle.com/code/jhoward/why-you-should-use-a-framework

The contents should be mostly known to you, because these contents are also based on chapter 4, which we have already worked on. We repeat the basics again with a new data set to consolidate our knowledge.



#Practical part (Assignment, May 31)

The following task is a binary classification task. The first column is our target. All variables are categorical variables from which you have to create dummy variables. The target column has only the property Q or F, which is to be modeled. As always, please create a train and a test data set, e.g. 80:20 or 90:10. Your goal is to create a neural network that best predicts the target column. Use probabilities with the sigmoid function as discussed in the theory. When designing your neural network, play with a few different numbers and sizes of layers and different activation functions.

To validate your model, you can compare your results with a logistic regression model. (Note: This data set should allow you to achieve very high accuracies: > 98% maybe even >99%) You can see how these results vary when you use 50% for testing and 50% for training.

In [ ]:
import pandas as pd
from google.colab import drive
from google.colab import data_table
import matplotlib.pyplot as plt
data_table.enable_dataframe_formatter()

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
import numpy as np
from torch import tensor
import torch

from fastai.data.transforms import RandomSplitter


In [ ]:
%cd './drive/My Drive/Digital Organisations'

/content/drive/My Drive


In [ ]:
%cd 'Digital Organisations'

/content/drive/My Drive/Digital Organisations


In [ ]:
data = pd.read_csv('data_homework_6.csv')

In [ ]:
data.head(10)

target variable_1 variable_2 variable_3 variable_4 variable_5 variable_6  \
0      Q          Y          T          O          U          Q          G   
1      F          Y          T          Z          U          B          G   
2      F          C          T          X          U          M          G   
3      Q          Y          Z          X          U          Q          G   
4      F          Y          T          H          G          O          G   
5      F          Y          Z          Z          U          B          G   
6      F          C          T          X          U          B          G   
7      F          C          Z          X          U          M          G   
8      Q          Y          Z          X          U          Q          G   
9      F          C          T          Z          U          B          G   

  variable_7 variable_8 variable_9  ... variable_13 variable_14 variable_15  \
0          D          O          L  ...           T           X           X   
1          D          C          L  ...           T           X           X   
2          D          C          O  ...           T           X           X   
3          D          O          O  ...           T           X           X   
4          X          C          L  ...           T           X           X   
5          D          C          O  ...           T           X           X   
6          D          C          H  ...           T           X           X   
7          D          C          O  ...           T           X           X   
8          D          O          Q  ...           T           X           X   
9          D          C          H  ...           T           X           X   

  variable_16 variable_17 variable_18 variable_19 variable_20 variable_21  \
0           Q           X           P           Q           L           T   
1           Q           X           P           Q           O           O   
2           Q           X           P           Q           O           O   
3           Q           X           P           Q           L           T   
4           Q           X           P           F           O           B   
5           Q           X           P           Q           L           O   
6           Q           X           P           Q           L           O   
7           Q           X           P           Q           O           T   
8           Q           X           P           Q           L           W   
9           Q           X           P           Q           L           T   

  variable_22  
0           V  
1           H  
2           N  
3           V  
4           H  
5           H  
6           N  
7           N  
8           H  
9           N  

[10 rows x 23 columns]

In [ ]:
data.isna().sum()

target         0
variable_1     0
variable_2     0
variable_3     0
variable_4     0
variable_5     0
variable_6     0
variable_7     0
variable_8     0
variable_9     0
variable_10    0
variable_11    0
variable_12    0
variable_13    0
variable_14    0
variable_15    0
variable_16    0
variable_17    0
variable_18    0
variable_19    0
variable_20    0
variable_21    0
variable_22    0
dtype: int64

In [ ]:
data.describe(include=[object])


target variable_1 variable_2 variable_3 variable_4 variable_5  \
count    8124       8124       8124       8124       8124       8124   
unique      2          6          4         10          2          9   
top         F          Y          Z          O          G          O   
freq     4208       3656       3244       2284       4748       3528   

       variable_6 variable_7 variable_8 variable_9  ... variable_13  \
count        8124       8124       8124       8124  ...        8124   
unique          2          2          2         12  ...           4   
top             G          D          C          C  ...           T   
freq         7914       6812       5612       1728  ...        4936   

       variable_14 variable_15 variable_16 variable_17 variable_18  \
count         8124        8124        8124        8124        8124   
unique           9           9           1           4           3   
top              X           X           Q           X           P   
freq          4464        4384        8124        7924        7488   

       variable_19 variable_20 variable_21 variable_22  
count         8124        8124        8124        8124  
unique           5           9           6           7  
top              Q           X           W           E  
freq          3968        2388        4040        3148  

[4 rows x 23 columns]

In [ ]:
target = data['target']

In [ ]:
target

0       Q
1       F
2       F
3       Q
4       F
       ..
8119    F
8120    F
8121    F
8122    Q
8123    F
Name: target, Length: 8124, dtype: object

In [ ]:
mapping = {"Q": 1, "F": 0}
numerical_target = [mapping[val] for val in target]

# Convert list to a tensor
t_dep = tensor(numerical_target)

In [ ]:
#get dummies:

df = pd.get_dummies(data)

In [ ]:
df.head(10)

target_F  target_Q  variable_1_C  variable_1_D  variable_1_G  variable_1_L  \
0         0         1             0             0             0             0   
1         1         0             0             0             0             0   
2         1         0             1             0             0             0   
3         0         1             0             0             0             0   
4         1         0             0             0             0             0   
5         1         0             0             0             0             0   
6         1         0             1             0             0             0   
7         1         0             1             0             0             0   
8         0         1             0             0             0             0   
9         1         0             1             0             0             0   

   variable_1_T  variable_1_Y  variable_2_G  variable_2_H  ...  variable_21_T  \
0             0             1             0             0  ...              1   
1             0             1             0             0  ...              0   
2             0             0             0             0  ...              0   
3             0             1             0             0  ...              1   
4             0             1             0             0  ...              0   
5             0             1             0             0  ...              0   
6             0             0             0             0  ...              0   
7             0             0             0             0  ...              1   
8             0             1             0             0  ...              0   
9             0             0             0             0  ...              1   

   variable_21_W  variable_21_Z  variable_22_E  variable_22_H  variable_22_M  \
0              0              0              0              0              0   
1              0              0              0              1              0   
2              0              0              0              0              0   
3              0              0              0              0              0   
4              0              0              0              1              0   
5              0              0              0              1              0   
6              0              0              0              0              0   
7              0              0              0              0              0   
8              1              0              0              1              0   
9              0              0              0              0              0   

   variable_22_N  variable_22_Q  variable_22_V  variable_22_X  
0              0              0              1              0  
1              0              0              0              0  
2              1              0              0              0  
3              0              0              1              0  
4              0              0              0              0  
5              0              0              0              0  
6              1              0              0              0  
7              1              0              0              0  
8              0              0              0              0  
9              1              0              0              0  

[10 rows x 119 columns]

In [ ]:
df_indep = df.iloc[:, 2:]


In [ ]:
df_indep

variable_1_C  variable_1_D  variable_1_G  variable_1_L  variable_1_T  \
0                0             0             0             0             0   
1                0             0             0             0             0   
2                1             0             0             0             0   
3                0             0             0             0             0   
4                0             0             0             0             0   
...            ...           ...           ...           ...           ...   
8119             0             0             0             1             0   
8120             0             0             0             0             0   
8121             0             0             1             0             0   
8122             0             0             0             1             0   
8123             0             0             0             0             0   

      variable_1_Y  variable_2_G  variable_2_H  variable_2_T  variable_2_Z  \
0                1             0             0             1             0   
1                1             0             0             1             0   
2                0             0             0             1             0   
3                1             0             0             0             1   
4                1             0             0             1             0   
...            ...           ...           ...           ...           ...   
8119             0             0             0             1             0   
8120             1             0             0             1             0   
8121             0             0             0             1             0   
8122             0             0             0             0             1   
8123             1             0             0             1             0   

      ...  variable_21_T  variable_21_W  variable_21_Z  variable_22_E  \
0     ...              1              0              0              0   
1     ...              0              0              0              0   
2     ...              0              0              0              0   
3     ...              1              0              0              0   
4     ...              0              0              0              0   
...   ...            ...            ...            ...            ...   
8119  ...              0              0              0              0   
8120  ...              0              1              0              0   
8121  ...              0              0              0              0   
8122  ...              0              1              0              0   
8123  ...              0              0              0              0   

      variable_22_H  variable_22_M  variable_22_N  variable_22_Q  \
0                 0              0              0              0   
1                 1              0              0              0   
2                 0              0              1              0   
3                 0              0              0              0   
4                 1              0              0              0   
...             ...            ...            ...            ...   
8119              0              1              0              0   
8120              0              1              0              0   
8121              0              1              0              0   
8122              0              1              0              0   
8123              0              1              0              0   

      variable_22_V  variable_22_X  
0                 1              0  
1                 0              0  
2                 0              0  
3                 1              0  
4                 0              0  
...             ...            ...  
8119              0              0  
8120              0              0  
8121              0              0  
8122              0              0  
8123              0            

In [ ]:
t_indep = tensor(df_indep.values, dtype=torch.float)

In [ ]:
t_indep.shape

torch.Size([8124, 117])

In [ ]:
def init_coeffs(n_hidden=20):
    layer1 = (torch.rand(n_coeff, n_hidden)-0.5)/n_hidden
    layer2 = torch.rand(n_hidden, 1)-0.3
    const = torch.rand(1)[0]
    return layer1.requires_grad_(),layer2.requires_grad_(),const.requires_grad_()

import torch.nn.functional as F

def calc_preds(coeffs, indeps):
    l1,l2,const = coeffs
    res = F.relu(indeps@l1)
    res = res@l2 + const
    return torch.sigmoid(res)

def update_coeffs(coeffs, lr):
    for layer in coeffs:
        layer.sub_(layer.grad * lr)
        layer.grad.zero_()

In [ ]:
torch.manual_seed(442)

n_coeff = t_indep.shape[1]
coeffs = torch.rand(n_coeff)-0.5
coeffs

tensor([-0.4629,  0.1386,  0.2409, -0.2262, -0.2632, -0.3147,  0.4876,  0.3136,
         0.2799, -0.4392,  0.2103,  0.3625,  0.1722,  0.2324, -0.3575, -0.0010,
        -0.1833, -0.2411,  0.0489,  0.0866, -0.0534,  0.3132, -0.1487, -0.2551,
         0.3328,  0.1292,  0.2361, -0.2622,  0.4051, -0.2674, -0.2312,  0.1147,
         0.4072,  0.2834,  0.0835, -0.0504,  0.4354, -0.3408, -0.4552,  0.1447,
        -0.4648, -0.3039, -0.1297, -0.0850,  0.4682,  0.3973, -0.4849,  0.2098,
        -0.3018,  0.4185,  0.1089,  0.0791, -0.1708, -0.1882,  0.4861, -0.2534,
        -0.2502, -0.0770,  0.3336, -0.4975, -0.2561,  0.0892, -0.4670,  0.3725,
        -0.1095,  0.3443, -0.3448,  0.1112, -0.2866,  0.0245, -0.1640, -0.0845,
        -0.1318,  0.3686,  0.3743,  0.4772, -0.0329, -0.3076,  0.1449,  0.3728,
         0.1066, -0.1043, -0.4297, -0.0069, -0.2685,  0.2132, -0.0946, -0.4802,
         0.1940,  0.0919,  0.2913, -0.2694,  0.4454, -0.2993,  0.1581,  0.3215,
        -0.1481,  0.2920,  0.0677,  0.27

In [ ]:
t_indep*coeffs


tensor([[-0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.2618,  0.0000],
        [-0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.0000,  0.0000],
        [-0.4629,  0.0000,  0.0000,  ...,  0.0000, -0.0000,  0.0000],
        ...,
        [-0.0000,  0.0000,  0.2409,  ...,  0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.0000,  0.0000]])

In [ ]:
vals,indices = t_indep.max(dim=0)
t_indep = t_indep / vals

In [ ]:
t_indep*coeffs

tensor([[-0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.2618,  0.0000],
        [-0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.0000,  0.0000],
        [-0.4629,  0.0000,  0.0000,  ...,  0.0000, -0.0000,  0.0000],
        ...,
        [-0.0000,  0.0000,  0.2409,  ...,  0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.0000,  0.0000]])

In [ ]:
t_indep = t_indep / vals


In [ ]:
preds = (t_indep*coeffs).sum(axis=1)


In [ ]:
preds[:10]


tensor([ 1.1211,  0.1683,  1.1884,  0.9827, -0.0693, -0.1522,  1.4092,  0.5461,
         1.6326,  1.5236])

In [ ]:
loss = torch.abs(preds-t_dep).mean()
loss

tensor(0.9183)

In [ ]:
def calc_preds(coeffs, indeps): return (indeps*coeffs).sum(axis=1)
def calc_loss(coeffs, indeps, deps): return torch.abs(calc_preds(coeffs, indeps)-deps).mean()

In [ ]:
coeffs.requires_grad_()


tensor([-0.4629,  0.1386,  0.2409, -0.2262, -0.2632, -0.3147,  0.4876,  0.3136,
         0.2799, -0.4392,  0.2103,  0.3625,  0.1722,  0.2324, -0.3575, -0.0010,
        -0.1833, -0.2411,  0.0489,  0.0866, -0.0534,  0.3132, -0.1487, -0.2551,
         0.3328,  0.1292,  0.2361, -0.2622,  0.4051, -0.2674, -0.2312,  0.1147,
         0.4072,  0.2834,  0.0835, -0.0504,  0.4354, -0.3408, -0.4552,  0.1447,
        -0.4648, -0.3039, -0.1297, -0.0850,  0.4682,  0.3973, -0.4849,  0.2098,
        -0.3018,  0.4185,  0.1089,  0.0791, -0.1708, -0.1882,  0.4861, -0.2534,
        -0.2502, -0.0770,  0.3336, -0.4975, -0.2561,  0.0892, -0.4670,  0.3725,
        -0.1095,  0.3443, -0.3448,  0.1112, -0.2866,  0.0245, -0.1640, -0.0845,
        -0.1318,  0.3686,  0.3743,  0.4772, -0.0329, -0.3076,  0.1449,  0.3728,
         0.1066, -0.1043, -0.4297, -0.0069, -0.2685,  0.2132, -0.0946, -0.4802,
         0.1940,  0.0919,  0.2913, -0.2694,  0.4454, -0.2993,  0.1581,  0.3215,
        -0.1481,  0.2920,  0.0677,  0.27

In [ ]:
loss = calc_loss(coeffs, t_indep, t_dep)
loss

tensor(0.9183, grad_fn=<MeanBackward0>)

In [ ]:
loss.backward()


In [ ]:
coeffs.grad


tensor([ 5.9084e-03, -2.4618e-04,  1.6100e-01, -7.8287e-02,  3.9389e-03,
         3.0281e-02,  1.9104e-01,  0.0000e+00, -6.0069e-02, -8.3703e-03,
         6.6470e-03,  2.4618e-04, -2.6096e-02,  1.2211e-01, -9.0103e-02,
         9.8474e-04, -9.8474e-04, -9.8474e-04,  2.8804e-02,  8.1979e-02,
        -1.4451e-01,  2.6711e-01,  3.7174e-02, -2.9542e-03,  4.7514e-02,
         4.2836e-02, -4.4313e-03,  1.1891e-01,  1.8710e-02, -6.7947e-02,
        -6.7208e-02, -2.5849e-02,  1.4845e-01,  1.4032e-01, -1.7725e-02,
         2.7917e-01, -1.5657e-01, -1.8808e-01, -2.4618e-03,  4.7514e-02,
        -1.1078e-02,  4.4313e-03,  4.8744e-02, -7.8779e-03,  1.4673e-01,
         2.2157e-03,  1.2555e-02,  8.0502e-02, -1.0586e-02,  1.4968e-01,
        -2.7080e-02,  2.6563e-01,  3.9143e-02,  2.2403e-02,  2.3634e-02,
        -2.2821e-01, -2.7573e-02, -2.7573e-02,  1.7971e-01, -1.9695e-03,
         3.6928e-03,  1.0340e-02,  9.4535e-02,  1.4032e-02,  3.3973e-02,
        -4.4313e-03,  4.9237e-04,  5.6376e-02,  2.7

In [ ]:
loss = calc_loss(coeffs, t_indep, t_dep)
loss.backward()
coeffs.grad

tensor([ 1.1817e-02, -4.9237e-04,  3.2201e-01, -1.5657e-01,  7.8779e-03,
         6.0561e-02,  3.8208e-01,  0.0000e+00, -1.2014e-01, -1.6741e-02,
         1.3294e-02,  4.9237e-04, -5.2191e-02,  2.4421e-01, -1.8021e-01,
         1.9695e-03, -1.9695e-03, -1.9695e-03,  5.7607e-02,  1.6396e-01,
        -2.8902e-01,  5.3422e-01,  7.4348e-02, -5.9084e-03,  9.5027e-02,
         8.5672e-02, -8.8626e-03,  2.3781e-01,  3.7420e-02, -1.3589e-01,
        -1.3442e-01, -5.1699e-02,  2.9690e-01,  2.8065e-01, -3.5451e-02,
         5.5835e-01, -3.1315e-01, -3.7617e-01, -4.9237e-03,  9.5027e-02,
        -2.2157e-02,  8.8626e-03,  9.7489e-02, -1.5756e-02,  2.9345e-01,
         4.4313e-03,  2.5111e-02,  1.6100e-01, -2.1172e-02,  2.9936e-01,
        -5.4161e-02,  5.3127e-01,  7.8287e-02,  4.4806e-02,  4.7267e-02,
        -4.5643e-01, -5.5145e-02, -5.5145e-02,  3.5943e-01, -3.9389e-03,
         7.3855e-03,  2.0679e-02,  1.8907e-01,  2.8065e-02,  6.7947e-02,
        -8.8626e-03,  9.8474e-04,  1.1275e-01,  5.4

In [ ]:
loss = calc_loss(coeffs, t_indep, t_dep)
loss.backward()
with torch.no_grad():
    coeffs.sub_(coeffs.grad * 0.1)
    coeffs.grad.zero_()
    print(calc_loss(coeffs, t_indep, t_dep))

tensor(0.7530)


In [ ]:
trn_split,val_split=RandomSplitter(seed=42)(df)
trn_indep,val_indep = t_indep[trn_split],t_indep[val_split]
trn_dep,val_dep = t_dep[trn_split],t_dep[val_split]
len(trn_indep),len(val_indep)

(6500, 1624)

In [ ]:
coeffs = train_model(18, lr=0.05)


0.924; 0.880; 0.843; 0.810; 0.781; 0.753; 0.728; 0.705; 0.684; 0.665; 0.648; 0.632; 0.618; 0.605; 0.593; 0.582; 0.572; 0.563; 

In [ ]:
preds = calc_preds(coeffs, val_indep)
preds

tensor([ 1.1035, -1.3343,  0.5488,  ...,  0.4359,  0.1704,  1.4131],
       grad_fn=<SumBackward1>)

In [ ]:
results = val_dep.bool()==(preds>0.5)
results[:16]

tensor([ True,  True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True])

In [ ]:
results.float().mean()


tensor(0.7352)

In [ ]:
def acc(coeffs): return (val_dep.bool()==(calc_preds(coeffs, val_indep)>0.5)).float().mean()
acc(coeffs)

tensor(0.7352)

In [ ]:
def calc_preds(coeffs, indeps): return torch.sigmoid((indeps*coeffs).sum(axis=1))


In [ ]:
coeffs = train_model(lr=10)


0.490; 0.147; 0.146; 0.170; 0.091; 0.080; 0.071; 0.065; 0.059; 0.055; 0.052; 0.049; 0.046; 0.044; 0.042; 0.040; 0.039; 0.037; 0.036; 0.035; 0.034; 0.033; 0.032; 0.031; 0.031; 0.030; 0.029; 0.029; 0.028; 0.028; 

In [ ]:
acc(coeffs)


tensor(0.9883)

Neural Network


In [ ]:
def calc_preds(coeffs, indeps): return torch.sigmoid(indeps@coeffs)
def init_coeffs(): return (torch.rand(n_coeff, 1)*0.1).requires_grad_()


In [ ]:
trn_dep = trn_dep[:,None]
val_dep = val_dep[:,None]

In [ ]:
coeffs = train_model(lr=10)


0.507; 0.155; 0.154; 0.147; 0.142; 0.097; 0.086; 0.074; 0.066; 0.060; 0.055; 0.052; 0.049; 0.046; 0.044; 0.042; 0.041; 0.039; 0.038; 0.037; 0.036; 0.035; 0.034; 0.033; 0.032; 0.032; 0.031; 0.030; 0.030; 0.029; 

In [ ]:
acc(coeffs)

tensor(0.9846)

In [ ]:
def update_coeffs(coeffs, lr):
    coeffs.sub_(coeffs.grad * lr)
    coeffs.grad.zero_()

def one_epoch(coeffs, lr):
    loss = calc_loss(coeffs, trn_indep, trn_dep)
    loss.backward()
    with torch.no_grad(): update_coeffs(coeffs, lr)
    print(f"{loss:.3f}", end="; ")

def init_coeffs(): return (torch.rand(n_coeff)-0.5).requires_grad_()

def train_model(epochs=30, lr=0.01):
    torch.manual_seed(442)
    coeffs = init_coeffs()
    for i in range(epochs): one_epoch(coeffs, lr=lr)
    return coeffs



In [ ]:
coeffs = train_model(lr=10)


0.507; 0.155; 0.154; 0.147; 0.142; 0.097; 0.086; 0.074; 0.066; 0.060; 0.055; 0.052; 0.049; 0.046; 0.044; 0.042; 0.041; 0.039; 0.038; 0.037; 0.036; 0.035; 0.034; 0.033; 0.032; 0.032; 0.031; 0.030; 0.030; 0.029; 

In [ ]:
acc(coeffs)


tensor(0.9846)

In [ ]:
def init_coeffs():
    hiddens = [10, 10]  # <-- set this to the size of each hidden layer you want
    sizes = [n_coeff] + hiddens + [1]
    n = len(sizes)
    layers = [(torch.rand(sizes[i], sizes[i+1])-0.3)/sizes[i+1]*4 for i in range(n-1)]
    consts = [(torch.rand(1)[0]-0.5)*0.1 for i in range(n-1)]
    for l in layers+consts: l.requires_grad_()
    return layers,consts

import torch.nn.functional as F

def calc_preds(coeffs, indeps):
    layers,consts = coeffs
    n = len(layers)
    res = indeps
    for i,l in enumerate(layers):
        res = res@l + consts[i]
        if i!=n-1: res = F.relu(res)
    return torch.sigmoid(res)

def update_coeffs(coeffs, lr):
    layers,consts = coeffs
    for layer in layers+consts:
        layer.sub_(layer.grad * lr)
        layer.grad.zero_()

In [ ]:
coeffs = train_model(lr=2)


0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 0.516; 

In [ ]:
acc(coeffs)

tensor(0.4723)